stages:
  - validate
  - plan
  - apply

variables:
  TF_VERSION: "1.5.7"
  TF_ROOT: ".terraform"
  TF_WORKSPACE: "${CI_ENVIRONMENT_NAME}" # Automatically uat or prod

default:
  image: hashicorp/terraform:${TF_VERSION}
  before_script:
    - cd $TF_ROOT
    - terraform init -upgrade

validate:
  stage: validate
  script:
    - terraform fmt -check
    - terraform validate

plan:
  stage: plan
  script:
    - terraform workspace select $TF_WORKSPACE || terraform workspace new $TF_WORKSPACE
    - terraform plan -var-file="terraform.tfvars"
  environment:
    name: $TF_WORKSPACE
  only:
    refs:
      - branches
    variables:
      - $TF_WORKSPACE

apply:
  stage: apply
  script:
    - terraform workspace select $TF_WORKSPACE || terraform workspace new $TF_WORKSPACE
    - terraform apply -auto-approve -var-file="terraform.tfvars"
  environment:
    name: $TF_WORKSPACE
  only:
    refs:
      - main
      - uat
  when: manual
